In [31]:
import numpy as np

In [32]:
values = [1, 2, 3, 4, 5]
values = np.array(values) + 5

In [33]:
values

array([ 6,  7,  8,  9, 10])

In [34]:
values += 5

In [35]:
values

array([11, 12, 13, 14, 15])

In [36]:
x = np.multiply(values, 5)

In [37]:
x

array([55, 60, 65, 70, 75])

In [38]:
x = values * 5

In [39]:
x

array([55, 60, 65, 70, 75])

In [40]:
m = values.copy()
m*=0

In [41]:
m

array([0, 0, 0, 0, 0])

In [42]:
x = values * values

In [43]:
x

array([121, 144, 169, 196, 225])

In [44]:
values

array([11, 12, 13, 14, 15])

In [45]:
values * values

array([121, 144, 169, 196, 225])